# Chromatogram Calibration Peak Counts.R
#   User functions called: none
# Author: Fred Lytle
# Last edit: 10/06/2022
rm(list=ls())

# user supplied input
weight <- '1/x^2'# choices: 'none','var','1/x^2'

# data generated by "Chromatogram Peak Counts.R"
#     and summarized in "Chromatogram Peak Counts.docx"
# Note: the avg-values are the average of four replicate peak areas
#     the sd-values are the stdev of the mean via propagated replicate variance
conc <- c(50,100,200,250,500)
avg96 <- c(837.8,1942,3782,4516,8794)
avg21 <- c(601.0,1550,3217,3640,7682)
avg06 <- c(338.7,929.7,2134,2443,4925)
sd96 <- c(12.46,18.59,34.58,41.26,75.87)
sd21 <- c(7.821,17.75,31.59,33.07,57.59)
sd06 <- c(6.268,11.18,21.39,21.70,38.63)

# calculate the least-squares weights
if(weight == 'none'){
  weights96 <- weights21 <- weights06 <- rep(1,length(conc))
}else if(weight == 'var'){
  weights96 <- c(1/sd96[1]^2,1/sd96[2]^2,1/sd96[3]^2,1/sd96[4]^2,
                 1/sd96[5]^2)
  weights21 <- c(1/sd21[1]^2,1/sd21[2]^2,1/sd21[3]^2,1/sd21[4]^2,
                 1/sd21[5]^2)
  weights06 <- c(1/sd06[1]^2,1/sd06[2]^2,1/sd06[3]^2,1/sd06[4]^2,
                 1/sd06[5]^2)
}else{
  weights96 <- weights21 <- weights06 <- 1/conc^2
}

# generate the main graph
title <- 'Chromatography Calibration Count\n'
if(weight=='1/x^2'){title <- paste0(title,' Weighted (1/x)^2')
}else if(weight == 'none'){title <- paste0(title,'Unweighted')
}else{title <- paste0(title,' Weighted 1/var')}

plot(conc,avg96,xlim=c(0,500),ylim=c(-10,9000),
     xlab='Conc (ng/mL)',ylab='Peak Area (count x sec)',
     main=title,font.main=1,cex.main=1)
grid(col='gray10')
points(conc,avg21,pch=16)
points(conc,avg06,pch=2)
legend('topleft',c('1x96','4x21','10x06'),pch=c(1,16,2),bty='n')

# perform the least-squares fits, errors, and covariance
fit96 <- lm(avg96~conc,weights=weights96)
coef96 <- summary(fit96)$coef[,1]
error96 <- summary(fit96)$coef[,2]
cov96 <- summary(fit96)$cov[1,2]*summary(fit96)$sigma^2
fit21 <- lm(avg21~conc,weights=weights21)
coef21 <- summary(fit21)$coef[,1]
error21 <- summary(fit21)$coef[,2]
cov21 <- summary(fit21)$cov[1,2]*summary(fit21)$sigma^2
fit06 <- lm(avg06~conc,weights=weights06)
coef06 <- summary(fit06)$coef[,1]
error06 <- summary(fit06)$coef[,2]
cov06 <- summary(fit06)$cov[1,2]*summary(fit06)$sigma^2

# add regression lines to the main graph
abline(fit96)
abline(fit21)
abline(fit06)

# print the results
{
  cat(title,
      '\nDwell Time:\t\t  Value     Error      Covar',
      '\n\t96 Intercept:\t',coef96[1],'; ',error96[1],'; ',cov96,
      '\n\t96 Slope:\t',coef96[2],'; ',error96[2],
      '\n\t21 Intercept:\t',coef21[1],'; ',error21[1],'; ',cov21,
      '\n\t21 Slope:\t',coef21[2],'; ',error21[2],
      '\n\t06 Intercept:\t',coef06[1],'; ',error06[1],'; ',cov06,
      '\n\t06 Slope:\t',coef06[2],';  ',error06[2],'\n',sep='')
  
  cat('\nCount Slope Ratios:\t',
      c(coef96[2],coef21[2],coef06[2])/coef96[2])
}

