# Chromatogram Calibration Peak Rates.R
#   User functions called: none
# Author: Fred Lytle
# Last edit: 10/07/2022
rm(list=ls())

# user supplied input
weight <- '1/x^2'# choices: 'none','var','1/x^2'

# data generated by chromatogram_numeric_areas.R
# Note: the avg-values are the average of four replicate peak areas
#   the sd-values are the stdev across the four replicate areas
conc <- c(50,100,200,250,500)
avg96 <- c(8379.6833,18897.6333,36894.2167,43922.7000,84627.0462)
avg21 <- c(7103.7750,17703.2000,36701.8500,41220.8833,87751.5417)
avg06 <- c(5475.9750,15053.9750,34066.1000,39308.6867,78049.6433)
sd96 <- c(724.7420,987.8027,2553.5471,2453.2186,2611.6830)
sd21 <- c(903.0551,1053.0515,2938.5027,572.7656,1451.9506)
sd06 <- c(420.1698,1510.1468,2559.2724,1113.6135,4187.8509)

# calculate the least-squares weights
if(weight == 'none'){
  weights96 <- weights21 <- weights06 <- rep(1,length(conc))
}else if(weight == 'var'){
  weights96 <- c(1/sd96[1]^2,1/sd96[2]^2,1/sd96[3]^2,1/sd96[4]^2,
                 1/sd96[5]^2)
  weights21 <- c(1/sd21[1]^2,1/sd21[2]^2,1/sd21[3]^2,1/sd21[4]^2,
                 1/sd21[5]^2)
  weights06 <- c(1/sd06[1]^2,1/sd06[2]^2,1/sd06[3]^2,1/sd06[4]^2,
                 1/sd06[5]^2)
}else{
  weights96 <- weights21 <- weights06 <- 1/conc^2
}

# generate the main graph
title <- 'Chromatography Calibration Rate'
if(weight=='1/x^2'){title <- paste0(title,'\nWeighted (1/x^2)')
}else if(weight == 'none'){title <- paste0(title,'\nUnweighted')
}else{title <- paste0(title,' Weighted 1/var')}
plot(conc,avg96,xlim=c(0,500),ylim=c(-10,95000),
     xlab='Conc (ng/mL)',ylab='Peak Area (counts)',
     main=title,font.main=1,cex.main=1)
grid(col='gray10')
points(conc,avg21,pch=16)
points(conc,avg06,pch=2)
legend('topleft',c('1x96','4x21','10x06'),pch=c(1,16,2),bty='n')

# perform the least-squares fits, errors, and covariance
fit96 <- lm(avg96~conc,weights=weights96)
coef96 <- summary(fit96)$coef[,1]
error96 <- summary(fit96)$coef[,2]
cov96 <- summary(fit96)$cov[1,2]*summary(fit96)$sigma^2
fit21 <- lm(avg21~conc,weights=weights21)
coef21 <- summary(fit21)$coef[,1]
error21 <- summary(fit21)$coef[,2]
cov21 <- summary(fit21)$cov[1,2]*summary(fit21)$sigma^2
fit06 <- lm(avg06~conc,weights=weights06)
coef06 <- summary(fit06)$coef[,1]
error06 <- summary(fit06)$coef[,2]
cov06 <- summary(fit06)$cov[1,2]*summary(fit06)$sigma^2

# add regression lines to th emain graph
abline(fit96)
abline(fit21)
abline(fit06)

# print the results
{
  cat(title,
      '\nDwell Time:\t\t  Value     Error      Covar',
      '\n\t96 Intercept:\t',coef96[1],'; ',error96[1],'; ',cov96,
      '\n\t96 Slope:\t',coef96[2],'; ',error96[2],
      '\n\t21 Intercept:\t',coef21[1],'; ',error21[1],'; ',cov21,
      '\n\t21 Slope:\t',coef21[2],'; ',error21[2],
      '\n\t06 Intercept:\t',coef06[1],'; ',error06[1],'; ',cov06,
      '\n\t06 Slope:\t',coef06[2],';  ',error06[2],'\n')
  
  cat('\nRate Slope Ratios:\t',
      c(coef96[2],coef21[2],coef06[2])/coef96[2])
}

