# Flow Injection Calibration Count.R
#   User functions called: none
# Author: Fred Lytle
# Last edit: 10/07/2022
rm(list=ls())

# user supplied input
weight <- 'none' # choices: 'none','1/x^2'

# data generated by "Flow Injection Full Trace Count.R"
#     and summarized in "Flow Injection Plateau Counts.docx"
# Note: the avg-values are the average of three replicate peak areas
conc <- c(50,250,500,1000,1500)
avg96 <- c(624.3,3490,5796,11159,17057)
avg21 <- c(448.8,2892,4947,9644,14417)
avg06 <- c(267.6,1974,3434,6718,10021)

# calculate the least-squares weights
if(weight == 'none'){weights <- rep(1,length(conc))
}else{weights <- 1/conc^2}

# perform the least-squares fits, errors, and covariance
fit96 <- lm(avg96~conc,weights=weights)
coef96 <- summary(fit96)$coef[,1]
error96 <- summary(fit96)$coef[,2]
cv96 <- error96/coef96
cov96 <- summary(fit96)$cov[1,2]*summary(fit96)$sigma^2
fit21 <- lm(avg21~conc,weights=weights)
coef21 <- summary(fit21)$coef[,1]
error21 <- summary(fit21)$coef[,2]
cv21 <- error21/coef21
cov21 <- summary(fit21)$cov[1,2]*summary(fit21)$sigma^2
fit06 <- lm(avg06~conc,weights=weights)
coef06 <- summary(fit06)$coef[,1]
error06 <- summary(fit06)$coef[,2]
cv06 <- error06/coef06
cov06 <- summary(fit06)$cov[1,2]*summary(fit06)$sigma^2

# generate the main graph
title <- paste0('Flow Injection Calibration Count')
if(weight=='1/x^2'){title <- paste0(title,'\n(1/x)^2 Weighted')
}else{title <- paste0(title,'\nUnweighted')}
plot(conc,avg96,ylim=c(0,max(avg96)),xlim=c(0,1500),
     xlab='ng/mL',ylab='Dwell Time Count Sum',cex=1.25,
     main=title,
     font.main=1,cex.main=1)
grid(col='gray10')
points(conc,avg21,pch=16)
points(conc,avg06,pch=2)
abline(fit96)
abline(fit21)
abline(fit06)
legend('topleft',c('1x96','4x21','10x06'),pch=c(1,16,2),bty='n')

{
  cat(title,
      '\nDwell Time:\tValue;\t Error;\t\tCV\tCovar',
      '\n\t96 Intercept:\t',coef96[1],'; ',error96[1],'; ',
      cv96[1],'; ',cov96,
      '\n\t96 Slope:\t',coef96[2],'; ',error96[2],'; ',cv96[2],
      '\n\t21 Intercept:\t',coef21[1],'; ',error21[1],'; ',
      cv21[1],'; ',cov21,
      '\n\t21 Slope:\t',coef21[2],'; ',error21[2],'; ',cv21[2],
      '\n\t06 Intercept:\t',coef06[1],'; ',error06[1],'; ',
      cv06[1],';  ',cov06,
      '\n\t06 Slope:\t',coef06[2],'; ',error06[2],'; ',cv06[2],
      sep='','\n')
  
  cat('\nCount Slope Ratios:\t',
      c(coef96[2],coef21[2],coef06[2])/coef96[2])
}

# plot for publication
if(FALSE){
  library(plotrix)
  rateMean96 <- c(6503,36351,60374,116243,177676)
  twoord.plot(conc,avg96,conc,rateMean96,xlab='Concentration ng/mL',
              ylab='              Sum of Dwell Time Counts',
              rylab='              Avg of Dwell Time Rates',type='p',
              mar=c(5,4,2,4)+0.1,lytickpos=c(0,5000,10000,15000),
              rytickpos=c(round(c(0,5000,10000,15000)/0.096)),
              lpch=1,rpch=1,lcol='black',rcol='black',cex=1.25)
  points(conc,avg21,pch=16)
  points(conc,avg06,pch=2)
  grid(col='gray10')
  abline(fit96,lty=2,lwd=2)
  abline(fit21,lty=1)
  abline(fit06,lty=1)
}

# simpler plot for publication
if(FALSE){
  pdf(file.path("manuscript", "figures", "figure_05.pdf"),
      width = 6.5, height=5)
  par(mar=c(5,4,2,2)+0.1)# reduce upper margin
  {
    plot(conc,avg96,ylim=c(0,max(avg96)),xlim=c(0,1500),cex=1.25,
       xlab='Concentration ng/mL',ylab='Dwell Time Count Sum')
    grid(col='gray10')
    points(conc,avg21,pch=16)
    points(conc,avg06,pch=2)
    abline(fit96)
    abline(fit21)
    abline(fit06)
  }
  par(mar=c(5,4,4,2)+0.1)# restore upper margin
  dev.off()
}
